# Name of workflow
name: linter

# Trigger the workflow on push or pull request
on:
  - push
 
jobs:
  make-lint:
    name: Run Linter
    runs-on: ubuntu-lates

     strategy:
      # Node versions list
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - run: make install-deps
      - run: make lint
