# Name of workflow
name: Main-Linter

# Trigger the workflow on push or pull request
on:
  - push
 

jobs:
   make-lint:
   runs-on: ubuntu-latest
    steps:
       -name: Chechout
       uses: action/checkout@v2

       -name: runt lint
       run: make lint
