# Name of workflow
name: linter

# Trigger the workflow on push or pull request
on:
  - push
 
jobs:
   make-lint:
   name: Run Linter
   runs-on: ubuntu-latest
    steps:
       -name: Chechout
        uses: action/checkout@v2

       -name: run linter
        run: make lint
